import XCTest
@testable import Liner

final class LinerTests: XCTestCase {
    private var temporaryDirectories: [URL] = []

    override func tearDownWithError() throws {
        for directory in temporaryDirectories {
            try? FileManager.default.removeItem(at: directory)
        }

        temporaryDirectories = []
        try super.tearDownWithError()
    }

    func testEditableMetadataStartsClean() {
        let metadata = TrackMetadata(
            title: "Song",
            artist: "Artist",
            album: "Album",
            albumArtist: "Album Artist",
            track: NumberedMetadata(number: 1, total: 10),
            disc: NumberedMetadata(number: 1, total: 2),
            genre: "Rock",
            year: 2026,
            comment: "Draft",
            artwork: ArtworkMetadata(data: Data([0x01, 0x02]), mimeType: "image/jpeg")
        )

        let state = EditableTrackMetadata(original: metadata)

        XCTAssertEqual(state.current, metadata)
        XCTAssertFalse(state.hasChanges)
        XCTAssertTrue(state.dirtyFields.isEmpty)
        XCTAssertTrue(state.changes.isEmpty)
    }

    func testEditableMetadataTracksChangedFields() {
        let original = TrackMetadata(
            title: "Original",
            artist: "Artist",
            track: NumberedMetadata(number: 1, total: 10)
        )
        var state = EditableTrackMetadata(original: original)

        state.update(.title, to: .text("Edited"))
        state.update(.track, to: .indexed(NumberedMetadata(number: 2, total: 10)))

        XCTAssertTrue(state.hasChanges)
        XCTAssertEqual(state.dirtyFields, [.title, .track])
        XCTAssertEqual(
            state.changes,
            [
                TrackMetadataChange(
                    field: .title,
                    originalValue: .text("Original"),
                    currentValue: .text("Edited")
                ),
                TrackMetadataChange(
                    field: .track,
                    originalValue: .indexed(NumberedMetadata(number: 1, total: 10)),
                    currentValue: .indexed(NumberedMetadata(number: 2, total: 10))
                )
            ]
        )
    }

    func testEditableMetadataCanResetFieldAndAllChanges() {
        var state = EditableTrackMetadata(
            original: TrackMetadata(title: "Original", artist: "Artist")
        )

        state.update(.title, to: .text("Edited"))
        state.update(.artist, to: .empty)

        state.reset(.title)

        XCTAssertEqual(state.current.title, "Original")
        XCTAssertEqual(state.current.artist, nil)
        XCTAssertEqual(state.dirtyFields, [.artist])

        state.resetAll()

        XCTAssertEqual(state.current, state.original)
        XCTAssertFalse(state.hasChanges)
    }

    func testID3v2AudioTagStoreLoadsBasicFixtureMetadata() throws {
        let metadata = try ID3v2AudioTagStore().loadMetadata(from: fixtureURL(named: "liner-id3v23-basic.mp3"))

        XCTAssertEqual(metadata.title, "Fixture Tone")
        XCTAssertEqual(metadata.artist, "Liner Tests")
        XCTAssertEqual(metadata.album, "Liner Fixture Album")
        XCTAssertEqual(metadata.albumArtist, "Liner Tests")
        XCTAssertEqual(metadata.track, NumberedMetadata(number: 1, total: 1))
        XCTAssertEqual(metadata.disc, NumberedMetadata(number: 1, total: 1))
        XCTAssertEqual(metadata.genre, "Test")
        XCTAssertEqual(metadata.year, 2026)
        XCTAssertEqual(metadata.comment, "Generated by scripts/generate-audio-fixtures.sh")
    }

    func testID3v2AudioTagStoreReportsMissingFields() {
        let report = ID3v2AudioTagStore().loadMetadataReport(
            from: fixtureURL(named: "liner-id3v23-basic.mp3")
        )

        XCTAssertNil(report.error)
        XCTAssertEqual(report.missingFields, [.artwork])
    }

    func testID3v2AudioTagStoreReportsReadErrorsWithoutThrowingFromReport() throws {
        let folderURL = try makeTemporaryDirectory()
        let fileURL = folderURL.appendingPathComponent("empty.mp3")
        try Data().write(to: fileURL)

        let report = ID3v2AudioTagStore().loadMetadataReport(from: fileURL)

        XCTAssertEqual(report.metadata, TrackMetadata())
        XCTAssertEqual(report.error, .missingID3v2Tag)
        XCTAssertEqual(report.missingFields, Set(TrackMetadataField.allCases))
    }

    func testMP3ImportScannerDetectsOnlyMP3FilesInFolder() throws {
        let folderURL = try makeTemporaryDirectory()
        let nestedFolderURL = folderURL.appendingPathComponent("Album")
        try FileManager.default.createDirectory(at: nestedFolderURL, withIntermediateDirectories: true)
        let firstMP3URL = folderURL.appendingPathComponent("01 Intro.mp3")
        let secondMP3URL = nestedFolderURL.appendingPathComponent("02 Song.MP3")
        let textURL = folderURL.appendingPathComponent("notes.txt")
        try Data().write(to: firstMP3URL)
        try Data().write(to: secondMP3URL)
        try Data().write(to: textURL)

        let result = MP3ImportScanner().scan(urls: [folderURL])

        XCTAssertEqual(
            result.acceptedURLs,
            [firstMP3URL, secondMP3URL].map(\.standardizedFileURL)
        )
        XCTAssertEqual(
            result.skippedItems,
            [
                MP3ImportSkippedItem(
                    url: textURL.standardizedFileURL,
                    reason: .unsupportedFile
                )
            ]
        )
    }

    func testMP3ImportScannerReportsDuplicatesAndUnsupportedFiles() throws {
        let folderURL = try makeTemporaryDirectory()
        let mp3URL = folderURL.appendingPathComponent("song.mp3")
        let aacURL = folderURL.appendingPathComponent("song.m4a")
        try Data().write(to: mp3URL)
        try Data().write(to: aacURL)

        let result = MP3ImportScanner().scan(
            urls: [mp3URL, mp3URL, aacURL],
            existingURLs: [mp3URL.standardizedFileURL]
        )

        XCTAssertTrue(result.acceptedURLs.isEmpty)
        XCTAssertEqual(
            result.skippedItems,
            [
                MP3ImportSkippedItem(url: mp3URL.standardizedFileURL, reason: .duplicate),
                MP3ImportSkippedItem(url: mp3URL.standardizedFileURL, reason: .duplicate),
                MP3ImportSkippedItem(url: aacURL.standardizedFileURL, reason: .unsupportedFile)
            ]
        )
    }

    private func makeTemporaryDirectory() throws -> URL {
        let directoryURL = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: directoryURL, withIntermediateDirectories: true)
        temporaryDirectories.append(directoryURL)
        return directoryURL
    }

    private func fixtureURL(named fileName: String) -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Tests/Fixtures/Audio")
            .appendingPathComponent(fileName)
    }
}
