#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT_DIR/Tests/Fixtures/Audio"
BASIC_OUT_FILE="$OUT_DIR/liner-id3v23-basic.mp3"
JAPANESE_OUT_FILE="$OUT_DIR/liner-id3v23-japanese.mp3"
EMPTY_TAG_OUT_FILE="$OUT_DIR/liner-id3v23-empty-tags.mp3"
CORRUPT_TAG_OUT_FILE="$OUT_DIR/liner-id3v23-corrupt-size.mp3"

mkdir -p "$OUT_DIR"

if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "error: ffmpeg is required to generate audio fixtures." >&2
  echo "Install ffmpeg, then run scripts/generate-audio-fixtures.sh again." >&2
  exit 1
fi

generate_tone_fixture() {
  local frequency="$1"
  local out_file="$2"
  shift 2

  ffmpeg -hide_banner -loglevel error -y \
    -f lavfi \
    -i "sine=frequency=$frequency:duration=0.8:sample_rate=44100" \
    -map_metadata -1 \
    "$@" \
    -codec:a libmp3lame \
    -b:a 32k \
    -ac 1 \
    -id3v2_version 3 \
    -write_id3v1 0 \
    "$out_file"
}

print_generated_size() {
  local out_file="$1"
  local bytes
  bytes="$(wc -c < "$out_file" | tr -d ' ')"
  echo "generated $out_file ($bytes bytes)"
}

generate_tone_fixture 440 "$BASIC_OUT_FILE" \
  -metadata "title=Fixture Tone" \
  -metadata "artist=Liner Tests" \
  -metadata "album=Liner Fixture Album" \
  -metadata "album_artist=Liner Tests" \
  -metadata "track=1/1" \
  -metadata "disc=1/1" \
  -metadata "genre=Test" \
  -metadata "date=2026" \
  -metadata "comment=Generated by scripts/generate-audio-fixtures.sh"
print_generated_size "$BASIC_OUT_FILE"

generate_tone_fixture 660 "$JAPANESE_OUT_FILE" \
  -metadata "title=夜明けのテスト" \
  -metadata "artist=ライナー" \
  -metadata "album=日本語フィクスチャ" \
  -metadata "album_artist=テスト集団" \
  -metadata "track=2/12" \
  -metadata "disc=1/2" \
  -metadata "genre=電子音楽" \
  -metadata "date=2026" \
  -metadata "comment=コメント本文"
print_generated_size "$JAPANESE_OUT_FILE"

# Minimal ID3v2.3 headers used to cover parser edge cases without depending on
# ffmpeg's metadata writer behavior for empty or malformed tags.
printf '\x49\x44\x33\x03\x00\x00\x00\x00\x00\x00' > "$EMPTY_TAG_OUT_FILE"
print_generated_size "$EMPTY_TAG_OUT_FILE"

printf '\x49\x44\x33\x03\x00\x00\x00\x00\x00\x0A' > "$CORRUPT_TAG_OUT_FILE"
print_generated_size "$CORRUPT_TAG_OUT_FILE"
