#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT_DIR/Tests/Fixtures/Audio"
OUT_FILE="$OUT_DIR/liner-id3v23-basic.mp3"

mkdir -p "$OUT_DIR"

if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "error: ffmpeg is required to generate audio fixtures." >&2
  echo "Install ffmpeg, then run scripts/generate-audio-fixtures.sh again." >&2
  exit 1
fi

ffmpeg -hide_banner -loglevel error -y \
  -f lavfi \
  -i "sine=frequency=440:duration=0.8:sample_rate=44100" \
  -map_metadata -1 \
  -metadata "title=Fixture Tone" \
  -metadata "artist=Liner Tests" \
  -metadata "album=Liner Fixture Album" \
  -metadata "album_artist=Liner Tests" \
  -metadata "track=1/1" \
  -metadata "disc=1/1" \
  -metadata "genre=Test" \
  -metadata "date=2026" \
  -metadata "comment=Generated by scripts/generate-audio-fixtures.sh" \
  -codec:a libmp3lame \
  -b:a 32k \
  -ac 1 \
  -id3v2_version 3 \
  -write_id3v1 0 \
  "$OUT_FILE"

BYTES="$(wc -c < "$OUT_FILE" | tr -d ' ')"
echo "generated $OUT_FILE ($BYTES bytes)"
